# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='BAŞLIK')),
                ('content', models.TextField(verbose_name='İÇERİK')),
                ('publishing', models.DateTimeField(auto_now_add=True, verbose_name='YAYINLANMA TARİHİ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-publishing', 'id'],
            },
        ),
    ]
