# Generated by Django 2.0.2 on 2018-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='#tag1 #tag2', max_length=120, verbose_name='TAGS'),
        ),
    ]
